version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      STAGE: prod
    env_file:
      - .env.stage.prod
    ports:
      - '8080:3000'
    volumes:
      - /data/postgres:/data/postgres

  postgres:
    image: postgres:14
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
